# Comandos Úteis (Numpy & Pandas)

**Run Jupyter Notebook**
```cmd
jupyter notebook --NotebookApp.token=''
```

**Bibliotecas úteis**
-	Numpy: http://www.numpy.org/ 
-	Sklearn: https://scikit-learn.org/stable/ 
-	Pandas: https://pandas.pydata.org 
-	TensorFlow: https://www.tensorflow.org/?hl=pt-br 
-	Keras: https://keras.io/ 

**Google Colab**

*Para acessar arquivos do  Google Drive e copiá-los para usar no google colab notebook*
```python
# Access files from google drive
from google.colab import drive
drive.mount('/content/drive')

# Copy files to google colab notebook
!ls "/content/drive/My Drive/..."
!cp "/content/drive/My Drive/file.csv" "file.csv"
```


*Upload de Arquivos*
```python
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
    print('Uploaded file "{name}" {length} bytes'.format(name=fn, length=len(uploaded[fn])))
```


### Exemplos de Datasets

In [27]:
# Iris Dataset
from sklearn import datasets
iris = datasets.load_iris()
X, y = iris.data[:, :2], iris.target

In [28]:
import pydataset
pydataset.data()[:2] # lista os datasets disponíveis

dataset_id                                        title
0  AirPassengers  Monthly Airline Passenger Numbers 1949-1960
1        BJsales            Sales Data with Leading Indicator

In [29]:
iris = pydataset.data('iris')
iris[:2]

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1           5.1          3.5           1.4          0.2  setosa
2           4.9          3.0           1.4          0.2  setosa

### Display HTML

In [372]:
# Exibir conteúdo HTML
from IPython.display import display, HTML
display(HTML('<i> Data Science </i>'))

### Arrays Numpy

In [31]:
# importação do numpy
import numpy as np

In [373]:
# Definindo Arrays
a = np.array([1., .5, 2.5])
a

array([1. , 0.5, 2.5])

In [33]:
a = np.array([1., .5, 2.5], dtype = float)
a

array([1. , 0.5, 2.5])

In [34]:
# matrizes
m = np.array([[1,2,3], [4,5,6], [7,8,9],[7,8,9],[7,8,9],[7,8,9],[7,8,9]])

In [35]:
#dimensões do array
a.shape 

(3,)

In [36]:
# número de dimensões do array
a.ndim

1

In [37]:
# Número de elementos no array
a.size

3

In [38]:
# Criar um array de zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
# Criar um array de 1's
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
# semelhante ao range
np.arange(5, 50, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [43]:
# Um array com 50 valores linearmente espaçados entre 0 e 10
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [44]:
# Um array com valores constantes
np.full( (2, 2), 42)

array([[42, 42],
       [42, 42]])

In [45]:
# Array Matriz Identidade
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
# Matriz de valores aleatórios entre 0 e 1
np.random.random((3,3))

array([[0.6592188 , 0.58838662, 0.0810382 ],
       [0.88141909, 0.48922593, 0.36939908],
       [0.87251293, 0.13772288, 0.84428796]])

In [49]:
# valores inteiros aleatórios
np.random.randint(low = 10, high=14, size = 10)

array([12, 10, 10, 11, 10, 10, 10, 11, 11, 11])

In [52]:
# produto escalar
a = np.random.random((1,3))
b = np.random.random((3,1))
c = np.dot(a, b) # scalar product

In [62]:
# transporta de uma matriz
m = np.random.random((2,3))
np.transpose(m)

array([[0.75978335, 0.11880602],
       [0.82190773, 0.31123918],
       [0.76585106, 0.95808534]])

In [64]:
# comparações
m > .5

array([[ True,  True,  True],
       [False, False,  True]])

In [80]:
# converte o array para outro tipo de dados
arr = np.array(['1','2','3'])
display(arr)

arr = arr.astype(np.float32)
display(arr)

array(['1', '2', '3'], dtype='<U1')

array([1., 2., 3.], dtype=float32)

In [106]:
# Funções agregadoras

# soma
np.sum(m), m.sum()

# média
np.mean(m), m.mean()

# mínimo
np.min(m), m.min()

# máximo
np.max(m), m.max()

# mediana
np.median(m)

# desvio padrão
np.std(m), m.std()


(0.3006570743306509, 0.3006570743306509)

In [125]:
# randomizar as linhas de uma matriz m
m = np.array([[10,  1.62, 81.0], [20,  1.75, 85.0], [30,  1.79, 89.0], [40,  1.82, 92.0]])
display(m)

np.random.shuffle(m)
display(m)

array([[10.  ,  1.62, 81.  ],
       [20.  ,  1.75, 85.  ],
       [30.  ,  1.79, 89.  ],
       [40.  ,  1.82, 92.  ]])

array([[40.  ,  1.82, 92.  ],
       [10.  ,  1.62, 81.  ],
       [30.  ,  1.79, 89.  ],
       [20.  ,  1.75, 85.  ]])

In [127]:
# slicing: todas as linhas e todas as colunas
m[:, :]

array([[40.  ,  1.82, 92.  ],
       [10.  ,  1.62, 81.  ],
       [30.  ,  1.79, 89.  ],
       [20.  ,  1.75, 85.  ]])

In [128]:
# slicing: todas as linhas, colunas 0 e 1
m[:, 0:2]

array([[40.  ,  1.82],
       [10.  ,  1.62],
       [30.  ,  1.79],
       [20.  ,  1.75]])

In [130]:
# slicing: linhas 0 e 1
m[:2] 

array([[40.  ,  1.82, 92.  ],
       [10.  ,  1.62, 81.  ]])

In [131]:
# slicing: todas as linhas e a última coluna
m[:, -1]

array([92., 81., 89., 85.])

In [134]:
# slicing: todas as linhas exceto a última coluna
m[:, :-1]

array([[40.  ,  1.82],
       [10.  ,  1.62],
       [30.  ,  1.79],
       [20.  ,  1.75]])

In [157]:
# concatenar arrays horizontalmente
a, b = np.zeros((3,4)), np.ones((3,2))

np.hstack( (a,b) )

array([[0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1., 1.]])

In [162]:
# concatenar arrays horizontalmente
a, b = np.zeros((3,4)), np.ones((3,2))

np.concatenate( (a, b), axis=1) # eixo 1

array([[0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1., 1.]])

In [159]:
# concatenar arrays verticalmente
a, b = np.zeros((3,4)), np.ones((4,4))

np.vstack( (a,b) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [160]:
# concatenar arrays verticalmente
a, b = np.zeros((3,4)), np.ones((4,4))

np.concatenate( (a, b), axis=0) # eixo 0

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [174]:
# Contador
from collections import Counter
votos = Counter(['A', 'A','B','A','A','A','B','C','C','C','C','C', 'E','E','D','D','D',])
votos

Counter({'A': 5, 'B': 2, 'C': 5, 'E': 2, 'D': 3})

In [177]:
# Os três elementos mais frequentes
votos.most_common(3)

[('A', 5), ('C', 5), ('D', 3)]

In [184]:
# O elemento mais frequente
mais_freq, ocorrencias = votos.most_common(1)[0]
mais_freq, ocorrencias

('A', 5)

In [188]:
# executar comandos do sistema operacional
!ls datasets/

iris.csv


### Pandas

- https://pandas.pydata.org
- Construído sobre o NumPy
- Fornece estruturas de dados e ferramentas para análise de dados com Python 3

In [182]:
# Importar o pandas
import pandas as pd 

In [202]:
# Carregar .CSV
df = pd.read_csv('datasets/iris.csv', delimiter=';')

In [203]:
# Carregar .CSV
df = pd.read_csv('datasets/iris.csv')

In [374]:
# Carregar de uma base de dados
try:
    from sqlalchemy import create_engine
    engine = create_engine('postgresql://us:pa@localhost:port/db')
    table_names = engine.table_names()
    df=pd.read_sql_query('select * from Tabela')
except:
    pass

In [204]:
# Criar uma cópia do dataset
ds = df.copy()

In [375]:
# Descrição do dataset
ds.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  891.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   13.002015    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   22.000000    0.000000   
50%     446.000000    0.000000    3.000000   29.699118    0.000000   
75%     668.500000    1.000000    3.000000   35.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [213]:
# Amostragem do Dataset: forma 1
sampling = ds.sample(frac=0.5).reset_index(drop=True)
sampling.shape

(75, 5)

In [376]:
# Amostragem do Dataset: forma 2
from sklearn.utils import shuffle
shuffle(ds)[:75].shape

(75, 12)

In [377]:
# Informações
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            891 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          891 non-null object
Embarked       891 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


In [217]:
# Início do dataset
ds.head()

SepalLength  SepalWidth  PetalLength  PetalWidth         Name
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [218]:
# Fim do dataset
ds.tail()

SepalLength  SepalWidth  PetalLength  PetalWidth            Name
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

In [378]:
# Lista de colunas do objeto DataFrame
ds.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [382]:
# Para selecionar colunas no dataframe
df[ ['SepalLength', 'PetalLength', 'Name'] ].head()

SepalLength  PetalLength         Name
0          5.1          1.4  Iris-setosa
1          4.9          1.4  Iris-setosa
2          4.7          1.3  Iris-setosa
3          4.6          1.5  Iris-setosa
4          5.0          1.4  Iris-setosa

In [384]:
# Select columns and rows in DataFrame
df[0:3][['SepalLength', 'Name']]

SepalLength         Name
0          5.1  Iris-setosa
1          4.9  Iris-setosa
2          4.7  Iris-setosa

In [226]:
# Dimensions
ds.shape

(150, 5)

In [228]:
# Get the indexes
ds.index

RangeIndex(start=0, stop=150, step=1)

In [230]:
# Column Statistics
ds.SepalLength.describe()

count    150.000000
mean       5.843333
std        0.828066
min        4.300000
25%        5.100000
50%        5.800000
75%        6.400000
max        7.900000
Name: SepalLength, dtype: float64

In [242]:
# Value counts in column
ds.Name.value_counts()

Iris-virginica     50
Iris-setosa        50
Iris-versicolor    50
Name: Name, dtype: int64

In [257]:
# Check nulls
titanic = pd.read_csv('datasets/titanic.csv')

nulls = pd.isnull(titanic['Age'])
nulls = pd.isnull(titanic.Age)

In [258]:
# Sum of nulls in column
titanic.Age.isnull().sum()
pd.isnull(titanic.Age).sum()

177

In [371]:
# Slice a Pandas DataFrame

# Use .loc to select a value by rows and column labels


temp = titanic.loc[0:3, 'Age']

temp = titanic.loc[0:3, ['Age']]
display(temp)

temp = titanic.loc[0:3, ['Age', 'Embarked']]
display(temp)

Age
0  22.0
1  38.0
2  26.0
3  35.0

Age Embarked
0  22.0        S
1  38.0        C
2  26.0        S
3  35.0        S

In [270]:
# Filtering null data
# Only rows with null age are displayed
titanic.loc[ pd.isnull(titanic.Age) ].head()

PassengerId  Survived  Pclass                           Name     Sex  Age  \
5             6         0       3               Moran, Mr. James    male  NaN   
17           18         1       2   Williams, Mr. Charles Eugene    male  NaN   
19           20         1       3        Masselmani, Mrs. Fatima  female  NaN   
26           27         0       3        Emir, Mr. Farred Chehab    male  NaN   
28           29         1       3  O'Dwyer, Miss. Ellen "Nellie"  female  NaN   

    SibSp  Parch  Ticket     Fare Cabin Embarked  
5       0      0  330877   8.4583   NaN        Q  
17      0      0  244373  13.0000   NaN        S  
19      0      0    2649   7.2250   NaN        C  
26      0      0    2631   7.2250   NaN        C  
28      0      0  330959   7.8792   NaN        Q

In [287]:
# Filtering Data
ds = titanic.copy()

ds[ ds.Sex == 'female'].head(3)

ds.loc[ ds['Age'] <= 1 ].head(3)

PassengerId  Survived  Pclass                           Name     Sex  \
78            79         1       2  Caldwell, Master. Alden Gates    male   
164          165         0       3   Panula, Master. Eino Viljami    male   
172          173         1       3   Johnson, Miss. Eleanor Ileen  female   

      Age  SibSp  Parch   Ticket     Fare    Cabin Embarked  
78   0.83      0      2   248738  29.0000  30.5058        S  
164  1.00      4      1  3101295  39.6875  30.5058        S  
172  1.00      1      1   347742  11.1333  28.2167        S

In [305]:
# Fill missing values  (Example 1)
mean_age = titanic.Age.mean()

titanic.Age = titanic.Age.fillna(mean_age)  # forma 1
titanic.Age.fillna(mean_age, inplace = True) # forma 2

In [306]:
# Fill missing values (Example 2)
most_often = titanic.Embarked.mode()
titanic.Embarked.fillna(most_often, inplace = True)

In [280]:
# Fill missing values (second example)
male = titanic[ titanic.Sex == 'male']
mean_male_age = male.Age.mean()
titanic[ titanic.Sex == 'male'] = titanic[ titanic.Sex == 'male'].fillna(mean_male_age)

female = titanic[ titanic.Sex == 'female']
female_male_age = female.Age.mean()
titanic[ titanic.Sex == 'female'] = titanic[ titanic.Sex == 'female'].fillna(female_male_age)

In [329]:
# Categorical data to numeric data (with pandas)
dummies = pd.get_dummies(iris.Species)

iris['setosa'] = dummies.setosa
iris['versicolor'] = dummies.versicolor
iris['virginica'] = dummies.virginica

display(dummies.head(2))

display(iris.head(2))

setosa  versicolor  virginica
1       1           0          0
2       1           0          0

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species  versicolor  \
1           5.1          3.5           1.4          0.2  setosa           0   
2           4.9          3.0           1.4          0.2  setosa           0   

   virginica  setosa  
1          0       1  
2          0       1

In [330]:
# Drop a column
if 'setosa' in iris.columns:
    iris.drop('setosa', axis=1, inplace=True)

In [331]:
# drop rows by a condition
titanic.drop( titanic[titanic.Age<5].index, inplace=True)

In [362]:
# Replace column data by condition
titanic.loc[titanic.Age<10, 'Age'] = 7.5

In [364]:
# Replace a column value by some condition
titanic.loc[titanic.Age < 0, 'Age'] = titanic.Age.mean()

In [338]:
# Select data by index
ds.iloc[42]

PassengerId                     43
Survived                         0
Pclass                           3
Name           Kraeff, Mr. Theodor
Sex                           male
Age                        29.6991
SibSp                            0
Parch                            0
Ticket                      349253
Fare                        7.8958
Cabin                      30.5058
Embarked                         C
Name: 42, dtype: object

In [346]:
# Slice a Pandas DataFrame
# use iloc to select a value by row and column


# Get all rows with columns 1,2 and 3
subset = titanic.iloc[:, 1: 4]

data = iris.iloc[:, :4]
targets = iris.iloc[:, 4]

subset.head()

Survived  Pclass                                                 Name
0         0       3                              Braund, Mr. Owen Harris
1         1       1  Cumings, Mrs. John Bradley (Florence Briggs Thayer)
2         1       3                               Heikkinen, Miss. Laina
3         1       1         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4         0       3                             Allen, Mr. William Henry

In [342]:
# Get all rows and last column
last_column = ds.iloc[:, -1]

In [349]:
# Get the values of a DataFrame

X = data.values # array numpy
y = targets.values # array numpy

display(X[:3])

display(y[:3])

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2]])

array(['setosa', 'setosa', 'setosa'], dtype=object)

In [354]:
# Uma Série: Um array indexado capaz de armazenar qualquer valor 
valores = [x for x in range(100)]
pd_qualidade = pd.Series(valores, name='Serie-Qualidade')

In [355]:
# Panda Series (Ex. 2)
uma_serie = pd.Series([10,20,30], name='Serie-Qualidade', index=['a','b','c'])

In [357]:
# Create a DataFrame (Ex.)
df_pd = pd.DataFrame(
    [
        [5, 6.5, 'A'], [5, 6.5, 'B']
    ],
    columns=['Qualidade', 'PH', 'Marca']
)

df_pd

Qualidade   PH Marca
0          5  6.5     A
1          5  6.5     B